services:
  - type: web
    name: rekt-user-management
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        value: https://amgeuvathssbhopfvubw.supabase.co
      - key: SUPABASE_SERVICE_KEY
        sync: false # This will be set manually in Render dashboard for security
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
